# Generated by Django 4.0.6 on 2022-09-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor_Summery',
            new_name='Doctor_Summary',
        ),
    ]
