# Generated by Django 4.0.6 on 2022-09-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_doctor_summery_doctor_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=10)),
                ('option2', models.CharField(max_length=10)),
                ('answer', models.CharField(max_length=10)),
            ],
        ),
    ]
