# Generated by Django 4.0.6 on 2022-09-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_appointment_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.CharField(choices=[('Dermatology', 'Dermatology'), ('Gastroenterology', 'Gastroenterology'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Obsterics/Gynecology', 'Obsterics/Gynecology'), ('Pediatrics', 'Pediatrics'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Urology', 'Urology'), ('Emergency medicine', 'Emergency_medicine')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Dermatology', 'Dermatology'), ('Cardiology', 'Cardiology'), ('Gastroenterology', 'Gastroenterology'), ('Neurology', 'Neurology'), ('Obsterics/Gynecology', 'Obsterics/Gynecology'), ('Pediatrics', 'Pediatrics'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Urology', 'Urology'), ('Emergency medicine', 'Emergency_medicine')], max_length=50),
        ),
    ]
