# Generated by Django 4.0.6 on 2022-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_appointment_services_alter_doctor_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('doa', models.CharField(max_length=100)),
                ('consultationFee', models.FloatField()),
                ('docFees', models.FloatField()),
                ('miscCharge', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
