# Generated by Django 4.0.6 on 2022-09-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_docfees_billing_docfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bill_generated',
            field=models.BooleanField(default=False),
        ),
    ]
