# Generated by Django 4.0.6 on 2022-09-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appointment_bill_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='consultationFee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='contactno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='doa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='docFee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='miscCharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
