# Generated by Django 4.0.6 on 2022-09-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_billing_user_alter_billing_billno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment'),
        ),
    ]
