# Generated by Django 4.0.6 on 2022-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_billing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.CharField(choices=[('Dermatology', 'Dermatology'), ('Gastroenterology', 'Gastroenterology'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Obsterics/Gynecology', 'Obsterics/Gynecology'), ('Pediatrics', 'Pediatrics'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Urology', 'Urology'), ('Emergency medicine', 'Emergency medicine')], max_length=100),
        ),
    ]
