# Generated by Django 4.0.6 on 2022-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Dermatology', 'Dermatology'), ('Cardiology', 'Cardiology'), ('Gastroenterology', 'Gastroenterology'), ('Neurology', 'Neurology'), ('Obsterics/Gynecology', 'Obsterics/Gynecology'), ('Pediatrics', 'Pediatrics'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Urology', 'Urology'), ('Emergency medicine', 'Emergency medicine')], max_length=50),
        ),
    ]
